In [2]:
# import necessary packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [6]:
# load data
spam_df = pd.read_csv("E:\MyCourse\Intro-to-Machine-Learning-main\spam.csv")
spam_df.sample(5)

Category                                            Message
4902      ham       Taka lor. Wat time u wan 2 come n look 4 us?
3977      ham                I wish u were here. I feel so alone
3194      ham  I will lick up every drop :) are you ready to ...
2776      ham                    We confirm eating at esplanade?
256       ham  Don't necessarily expect it to be done before ...

In [9]:
#inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [10]:
# convert ham/spam to numeric data
spam_df["Spam"]= spam_df["Category"].apply(lambda x: 1 if x=="spam" else 0)

In [11]:
# view
spam_df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [13]:
# create train/test split
X_train, X_test, y_train, y_test = train_test_split(spam_df.Message, spam_df.Spam, test_size=0.2)

In [16]:
# find word count and store the data as matrix
cv =CountVectorizer()
X_train_count = cv.fit_transform(X_train)

In [20]:
#checking X_train_count
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
# train model
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [23]:
# pre-test ham
email_ham = ["Hey, wanna meet up for the game?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [26]:
# pre-test spam
email_spam = ["Hurry up!click on the link now to get the prize mmoney"]
email_spam_count= cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [27]:
# test model
X_test_count = cv.transform(X_test)
model.score(X_test_count, y_test)



0.9856502242152466